name: Update Github Page
on:
    schedule:
        -   cron: '42 2 * * *'

jobs:
    update:
        name: Re Generate pages
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN }}
            CONTENTFUL_CONTENT_PREVIEW_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_CONTENT_PREVIEW_API_ACCESS_TOKEN }}
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: 7.4
                id: php

            -   name: Validate composer.json and composer.lock
                run: cd application && composer validate

            -   name: Install dependencies
                run: cd application && composer install --prefer-dist --no-progress --no-suggest --no-interaction

            -   name: Generate
                run: php application/bin/generate.php > index.html

            -   name: Commit and push if changed
                run: |
                    git diff
                    git config --global user.email "morel.seb@gmail.com"
                    git config --global user.name "Plopix"
                    git commit -am "Auto-Update Pages"
                    git push
